name: Update Data
on:
  push:
    paths:
    - data/UNO Service Learning Data Sheet De-Identified Version(1).xlsx
  schedule: 
  - cron: '0 0 1 * *'
jobs:
  run-steamlit:
    runs on: ubuntu-latest
    steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirement.txt
    - name: Run App
      run: |
        streamlit run streamlit_app.py
        
